/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <gtkpanda/gtkpanda.h>
#include <glade/glade.h>
#include "callbacks.h"

int
main (int argc, char *argv[])
{
  GladeXML *xml;
  GtkWidget *html;
  GtkWidget *preview;
  GtkWidget *clist;
  int i;
  char text[3][50];
  char *texts[3];
  gchar *data;
  gsize size;

  gtk_init(&argc, &argv);
  glade_init();

  xml = glade_xml_new("gtkpanda.glade", NULL);

  if (!xml) {
    g_warning("something bad happened while creating the interface");
    return 1;
  }

  glade_xml_signal_autoconnect(xml);

  html = glade_xml_get_widget_by_long_name (xml,
    "window1.fixed1.pandahtml1");
  gtk_panda_html_set_uri(GTK_PANDA_HTML(html),
    "http://www.orca.med.or.jp");

  preview = glade_xml_get_widget_by_long_name (xml,
    "window1.fixed1.pandaps1");
  g_file_get_contents("test.pdf", &data, &size, NULL);
  gtk_panda_pdf_set(GTK_PANDA_PDF(preview), size, data);

  clist = glade_xml_get_widget_by_long_name (xml,
    "window1.fixed1.scrolledwindow1.pandaclist1");
  for (i = 0; i < 3; i++){
      texts[i] = text[i];
      sprintf (text[i], "列 %d", i);
  }

  for (i = 0; i < 100; i++){
      sprintf (text[0], "行 %d", i);
  }

  gtk_main ();
  return 0;
}

