/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <glade/glade.h>
#include "callbacks.h"

int
main (int argc, char *argv[])
{
  GladeXML *xml;

  gtk_init(&argc, &argv);
  glade_init();

  xml = glade_xml_new("basic.glade", NULL);

  if (!xml) {
    g_warning("something bad happened while creating the interface");
    return 1;
  }

  glade_xml_signal_autoconnect(xml);

  gtk_main ();
  return 0;
}

